version: '3.8'

services:
  postgres:
    image: postgres:16
    restart: always
    environment:
      POSTGRES_DB: ${DATABASE_NAME}  # Replace 'mydatabase' with your desired database name
      POSTGRES_USER: ${DATABASE_USERNAME}    # Replace 'myuser' with your desired username
      POSTGRES_PASSWORD: ${DATABASE_PASSWORD}  # Replace 'mypassword' with your desired password
    ports:
      - "5432:${DATABASE_PORT}"  # Expose PostgreSQL default port

    volumes:
      - postgres_data:/var/lib/postgresql/data  # Persist data using named volume

volumes:
  postgres_data:
    driver: local
